version: '3.3'

services:

  _mysql: &mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: intro
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql

  mysql56:
    <<: *mysql
    image: mysql:5.6
    ports:
      - "33066:3306"
    volumes:
      - mysql56:/var/lib/mysql

  mysql57: &mysql57
    <<: *mysql
    image: mysql:5.7
    ports:
      - "33067:3306"
    volumes:
      - mysql57:/var/lib/mysql

  mysql57-src:
    <<: *mysql57
    ports:
      - "33070:3306"
    volumes:
      - src:/var/lib/mysql

  mysql57-slave:
    <<: *mysql57
    ports:
      - "33079:3306"
    links:
      - mysql57
      - mysql57-src
    volumes:
      - rep:/var/lib/mysql
      - ./mysql/crash_safe.cnf:/etc/mysql/conf.d/crash_safe.cnf

  mysql80:
    <<: *mysql
    image: mysql:8.0
    ports:
      - "33068:3306"
    volumes:
      - mysql80:/var/lib/mysql

volumes:
  mysql56:
  mysql57:
  src:
  rep:
  mysql80:
