SHOW SLAVE STATUS;

CHANGE MASTER TO
MASTER_HOST = 'mysql57'
, MASTER_PORT = 3306
, MASTER_USER = 'root'
, MASTER_PASSWORD = 'intro'
FOR CHANNEL 'master1';

CHANGE MASTER TO
MASTER_HOST = 'mysql57-src'
, MASTER_PORT = 3306
, MASTER_USER = 'root'
, MASTER_PASSWORD = 'intro'
FOR CHANNEL 'master2';

SHOW SLAVE STATUS;

START SLAVE FOR CHANNEL 'master1';

START SLAVE FOR CHANNEL 'master2';

STOP SLAVE IO_THREAD FOR CHANNEL 'master1';

STOP SLAVE IO_THREAD FOR CHANNEL 'master2';
